#!/bin/sh
curl "https://raw.githubusercontent.com/lyh16/azc/main/azc" -s --output azc
touch zoom-meetings.txt
echo "Success."
echo ""
echo "NOTE: azc and your zoom-meetings.txt file are in: "$PWD
echo "------for God's sake remember this location"
